#!/usr/bin/env python3
"""Create the brethof-mind schema in SurrealDB.

Reads your projects.json and, for every project key, defines:
  - <key>        — curated memory table  (+ embedding/content/updated_at/obsolete indexes)
  - <key>_chat   — full chat archive     (+ embedding/session/timestamp/line_type/text indexes)
plus the project-independent `supersedes` graph relation.

Tables are SCHEMALESS (SurrealDB would create them lazily on first write
anyway) — the point of this script is the INDEXES, which must be declared
explicitly and make search fast. Everything is `IF NOT EXISTS`, so it is
safe to re-run after you add a project.

    python scripts/init_db.py            # apply
    python scripts/init_db.py --dry-run  # print the DDL only
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _config import load_config, project_keys, surreal_query  # noqa: E402


def build_ddl(keys: list[str], dim: int) -> str:
    lines: list[str] = [
        "-- Generated by scripts/init_db.py from projects.json.",
        "-- Field contract for the SCHEMALESS tables is documented in schemas.surql.",
        "",
        "-- Graph relation: new_record -> supersedes -> old_record.",
        "DEFINE TABLE IF NOT EXISTS supersedes TYPE RELATION SCHEMALESS PERMISSIONS NONE;",
        "DEFINE INDEX IF NOT EXISTS idx_supersedes_in  ON supersedes FIELDS in;",
        "DEFINE INDEX IF NOT EXISTS idx_supersedes_out ON supersedes FIELDS out;",
        "",
        "-- Full-text analyzer for search_memory: tokenize, lowercase, ascii-fold,",
        "-- and snowball-stem (english) so e.g. 'deploying' matches 'deploy'.",
        "DEFINE ANALYZER IF NOT EXISTS memory_text TOKENIZERS blank,class "
        "FILTERS lowercase,ascii,snowball(english);",
        "",
    ]
    for k in keys:
        lines += [
            f"-- ── project: {k} ─────────────────────────────────────────────",
            f"DEFINE TABLE IF NOT EXISTS {k} TYPE ANY SCHEMALESS PERMISSIONS NONE;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_embedding ON {k} FIELDS embedding "
            f"HNSW DIMENSION {dim} DIST COSINE;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_content_fts ON {k} FIELDS content "
            f"FULLTEXT ANALYZER memory_text BM25;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_title_fts   ON {k} FIELDS title "
            f"FULLTEXT ANALYZER memory_text BM25;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_updated   ON {k} FIELDS updated_at;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_obsolete  ON {k} FIELDS obsolete;",
            "",
            f"DEFINE TABLE IF NOT EXISTS {k}_chat TYPE ANY SCHEMALESS PERMISSIONS NONE;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_chat_embedding ON {k}_chat FIELDS embedding "
            f"HNSW DIMENSION {dim} DIST COSINE;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_chat_session ON {k}_chat FIELDS session_id;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_chat_ts      ON {k}_chat FIELDS timestamp;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_chat_ltype   ON {k}_chat FIELDS line_type;",
            f"DEFINE INDEX IF NOT EXISTS idx_{k}_chat_text    ON {k}_chat FIELDS text;",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    cfg = load_config()
    keys = project_keys(cfg)
    dim = int(cfg.get("embedding_dim", 384))
    if not keys:
        print("No projects defined in projects.json — nothing to do.", flush=True)
        return 1

    sd = cfg["surrealdb"]
    ns, db = sd["ns"], sd["db"]
    # A fresh SurrealDB has neither the namespace nor the database, and you
    # cannot header-select them until they exist — so create them first and
    # switch into them with USE, all in one root-context request.
    bootstrap = (
        f"DEFINE NAMESPACE IF NOT EXISTS {ns};\n"
        f"USE NS {ns};\n"
        f"DEFINE DATABASE IF NOT EXISTS {db};\n"
        f"USE NS {ns} DB {db};\n\n"
    )
    full = bootstrap + build_ddl(keys, dim)

    if "--dry-run" in sys.argv:
        print(full)
        return 0

    print(f"Applying schema to {sd['url']} (ns={ns} db={db})", flush=True)
    print(f"Projects: {', '.join(keys)}  |  embedding dim: {dim}", flush=True)
    try:
        # with_context=False: run at the connection root and switch context
        # via the USE statements inside the script (see bootstrap above).
        results = surreal_query(full, cfg, timeout=120.0, with_context=False)
    except Exception as e:
        print(f"FAILED to reach SurrealDB: {e}", flush=True)
        print("Is the DB up?  docker compose up -d", flush=True)
        return 1

    errors = [r for r in results if isinstance(r, dict) and r.get("status") == "ERR"]
    for e in errors[:10]:
        print(f"  ERR: {e.get('result')}", flush=True)
    ok = len(results) - len(errors)
    print(f"Done: {ok} statements OK, {len(errors)} errors.", flush=True)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
